version: "3.9"

services:
  # Mongo DB Container
  db:
    container_name: mongo-db-dev
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongodb_data_container_dev:/data/db
    networks:
      - db-dev-network
    restart: always
  # Backend Container
  backend:
    container_name: back-dev
    image: backend:dev
    environment:
      - DB_CONNECTION_STRING
      - JWT_SECRET
      - FORGET_PASSWORD_SECRET
      - SU_PASS
      - SU_EMAIL
      - SU_USERNAME
      - EMAIL_USER
      - EMAIL_PASS
      - GOOGLE_CREDIENTIALS_CLIENT_ID_flutter_android
      - GOOGLE_CREDIENTIALS_CLIENT_ID_flutter_web
      - GOOGLE_CREDIENTIALS_CLIENT_ID_web
    networks:
      - db-dev-network
    depends_on:
      - db
    restart: always
  # Static Content
  static-resources:
    container_name: resources
    image: nginx:latest
    restart: always
    volumes:
      - backend_assets:/usr/share/nginx/html/assets 
  # Frontend Container
  frontend:
    container_name: front-dev
    image: frontend:dev
    environment:
      - REACT_APP_BASE_URL
      - REACT_APP_GOOGLE_ID
      - REACT_APP_GOOGLE_SECRET
      - REACT_APP_GITHUB_ID
      - REACT_APP_GITHUB_SECRET
    restart: always
    depends_on:
      - backend
  # Cross Platform Container
  crossplatform:
    container_name: cross-dev
    image: cross:dev
    environment:
      - BASE_URL
      - MEDIA_URL
    restart: always
    depends_on:
      - backend
  testing:
    image: testing:dev
    container_name: testing-dev
    command: "--browser chrome --config video=false"
    depends_on:
      - frontend
    volumes:
      - test_results:/e2e/results
volumes:
  mongodb_data_container_dev:
  test_results:

networks:
  db-dev-network: